name: spartapp
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  imgur_service:
    path: packages/imgur_service
  imgur_repository:
    path: packages/imgur_repository
  local_storage_service:
    path: packages/local_storage_service
  dartz: ^0.10.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  generate: true
