name: imgur_service
description: Imgur Service
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.5.4

